### ISSUE TITLE
The update to the glyph for U+1E29C is undesired

### ISSUE THREAD

**Issue by Toby-3-Strands** [notofonts/toto#6]
**Is your feature request related to a problem? Please describe.**

The character used for the /w/ sound in Toto (unicode U+1E29C) looks like the one used for /l/ (U+1E2A0) except with an extra bit below - that extra bit was a dot in the original version of this font, but now it is a diagonal line.

When Dhaniram Toto, who designed the characters, first wrote this letter down, it was a dot.

Many of the other Toto letters do have a diagonal line under them, distinguishing them from another letter that would otherwise be identical - these are all vowels and the diagonal line indicates a breathy vowel. The equivalent modal vowel looks the same except for not having the diagonal line. The consonants don't have the diagonal line.

The first (proper) font made for Toto was called "Hispa" and was made by a volunteer who did an excellent job with it. However, this font designer had no knowledge of the Toto phonology or what sound each letter was representing. When he saw the letter for /l/ and then the one for /w/ which looked like the one for /l/ except with a dot, he probably thought he was seeing the same pattern as the modal and breathy vowel difference and made the dot into a diagonal line for consistency.

Noto Serif Toto is now the only font that represents the Toto characters in their proper place in unicode. This font is based on the existing Hispa font, but the one significant change made was changing the U+1E29C glyph to have a diagonal line instead of a dot.

Some time later this font got updates and that glyph was changed back to using a diagonal line. I don't know exactly when this happened, or why.

**Describe the solution you'd like**
Please revert the U+1E29C glyph to how it was originally, with a dot instead of a diagonal line

**Additional context**
I am the linguist who was working with Dhaniram Toto when he first designed the characters for his orthography. This is a picture of the paper he first wrote them down on.
![first expression](https://github.com/user-attachments/assets/7671378b-6ffd-4095-832a-ba82216c997d)
As you can see, he used a dot under the 'w' character
![first expression w](https://github.com/user-attachments/assets/b53133a6-fe6d-40ec-8730-9e30abeba458)

**Comment by Toby-3-Strands** [comment]
Sorry, after submitting this issue, I've just noticed https://github.com/notofonts/toto/issues/3
This should be taken as a request to reopen and revert the change from that issue

**Comment by Toby-3-Strands** [comment]
writing the glyph for /w/ as the same as the glyph for /l/ except with the breathiness indicator implies we consider /w/ to be a breathy version of /l/ which it is not.

**Comment by verdy-p** [comment]
This should be reported to the UTC and ISO, to investigate the case about its representative glyph in the Unicode and ISO charts. A single report by a font designer using this manual writing, and interpretation of this draft may not be enough. The UTC and ISO have also their own experts that approved the existing letter form. If a dot must should used (independantly of its interpretation as meaning "breathy" or not), this should be discussed there (as well as if /w/ is phonetically perceived as a consonant or a vowel).
May be the dot is an acceptable variant.

See the various encoding proposals and submitted samples before the release in Unicode 14.0 (September 2021):
* https://www.unicode.org/L2/L2019/19278-toto-script.pdf (18 June18 2019), including notably a sample of “Story of the Bees” by Prakash Toto. Toto Writer’s Guide, and other typesetted samples (not manual drafts).
* https://www.unicode.org/L2/L2019/19286-script-recs.pdf (22 July 2019)
* https://www.unicode.org/L2/L2019/19330-toto-script.pdf and https://www.unicode.org/wg2/docs/n5141-19330-toto-script.pdf (27 September 2019) 
* https://www.unicode.org/L2/L2019/19343-script-adhoc-recs.pdf (4 November 2019)
* https://www.unicode.org/L2/L2019/19323.htm (7-10 October 2019, revised 1 November 2019)

All these samples submitted to the UTC and WG2 showed a diagonal, not a dot. Nothing was changed during the alpha and beta review of the Unicode standard. So this issue is to actually to propose an update to the standard.

Note that the 5 "breathy vowels" (still using PUA's at U+E642, U+E644, U+E647, U+E649, U+E64C in L2/19278) were added to the proposal *after* the initial proposal of the consonant WA (that never changed) from a prior encoding request, and used the "breathy accent" (not decomposed) looking exactly like the diagonal present in consonant WA in all considered samples. The samples were taken in 2018, I don't know when the manual draft above was created, may be it was an early stage of the Toto script development which still used a dot (but possibly could cause confusion with letter PA, where the dot is centered in the loop and not below).

Are the two people names "Prakash Toto" and "Dhaniham Toto" refering the same person? Who is the right inventor or active promoter of the script? See also how the manual draft sample shown bove demonstrates very different attempts to design the glyphs, some of them already erased and replaced (notably for vowels). Is it likely that the glyph for WA was consistently changed to look like the stabilized vowel forms? Finally note that the UCS encoded 13 vowels, not just 12 as above and the draft also added an horizontal stroek above letter O (which was never found in the typesetted samples submitted to the UTC and WG2). IMHO, the draft above is just that: an early draft with various tries, not reflecting what was finally developped and promoted.

**Comment by Toby-3-Strands** [comment]
>  All these samples submitted to the UTC and WG2 showed a diagonal, not a dot.

indeed, that is because the Hispa font was the _only_ decent font available at the time. There was one other font, created by myself, but since that was my one and only attempt at making a font, I did a very poor job of it, and it came out rather shabby. I chose to submit the materials to the UTC using a decent font with a small defect, rather than a shabby font.

> Are the two people names "Prakash Toto" and "Dhaniham Toto" refering the same person?

These are different people. Prakash is the author of "Story of the Bees". Dhaniram designed the letters for the Toto alphabet.

> Who is the right inventor or active promoter of the script?

Dhaniram Toto invented the script, with input from myself regarding what phonemes are in the language that needed to be represented as letters in the alphabet. No one holds an official role of "promoter of the script" but in terms of which individuals are most active in promoting it, depending on how you define that, it would either be myself or Mercy Toto.

Indeed @verdy-p  you are correct that the manual draft sample I posted is an early draft, since it is, as I said, the very first expression of the script. Since then, a number of refinements and changes were made, especially in the vowels, as new information about the Toto phonology came to light.

Here is a photo of Dhaniram presenting the alphabet at the launch event for the Toto script that happened in April 2015:
![IMG_0122](https://github.com/user-attachments/assets/7a80eb52-53b3-4c2e-b01a-7d7768b126ca)

Unfortunately the alphabet chart in this photo is not clear, and Dhaniram's arm is covering the character used for /w/. But fortunately I still have the image used to create that poster:
![alphabet_t_r_b_colour](https://github.com/user-attachments/assets/0c4e6c76-293b-449c-97c9-b2b32f78611b)

This chart uses the shabby font that I created, which itself was based on the manual samples given to me by Dhaniram. As you can see the 'w' glyph has a dot under it. The dot is elongated, but nothing like the lines appearing under the breathy vowels.
Even after this event, more changes were made to the alphabet, however the change to the glyph for /w/ was unintended and came about purely because of the Hispa font created by Jordan Bell. Jordan had no knowledge of the Toto phonology when he created the font. I regret not asking for a correction of this glyph at that time, but I was just overjoyed that he had created such a beautiful font for the Toto script on a volunteer basis - I wasn't inclined to look a gift horse in the mouth, as the idiom goes.

**Comment by simoncozens** [comment]
OK, I'm convinced. Sorry, I should have listened to actual script users.

**Comment by verdy-p** [comment]
So now it's time to send a bug report to the UTC, to fix the charts.

**Comment by Toby-3-Strands** [comment]
@verdy-p yes you are right that I should submit a bug report also to the UTC. I'll do that when I'm able.

@simoncozens in the Noto fonts website the glyph still hasn't been reverted to the dot form. Has the version with this change not been released yet?
